linters:
  Comment:
    allowed: ^[/*]
  EmptyLineBetweenBlocks:
    enabled: false
  IdSelector:
    enabled: false
  ImportantRule:
    enabled: false
  LeadingZero:
    enabled: false
  NestingDepth:
    enabled: false
  PropertyCount:
    enabled: false
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    allow_element_with_class: true
    allow_element_with_attribute: true
  SelectorDepth:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: false
  SpaceAfterPropertyName:
    enabled: false
