linters:
  ColorVariable:
    enabled: false
  Comment:
    allowed: ^[/*]
  DeclarationOrder:
    enabled: false
  EmptyLineBetweenBlocks:
    enabled: false
  ElsePlacement:
    enabled: false
  IdSelector:
    enabled: false
  ImportPath:
    enabled: false
  ImportantRule:
    enabled: false
  LeadingZero:
    enabled: false
  NestingDepth:
    enabled: false
  PropertyCount:
    enabled: false
  PropertySortOrder:
    enabled: false
  QualifyingElement:
    allow_element_with_class: true
    allow_element_with_attribute: true
  SelectorDepth:
    enabled: false
  SelectorFormat:
    enabled: false
  SpaceAfterPropertyColon:
    enabled: false
  SpaceAfterPropertyName:
    enabled: false
  UrlFormat:
    enabled: false
  VendorPrefix:
    enabled: false
